---
- hosts: localhost
  tags: ["instructions"]
  roles:
    - role: instructions

- hosts: all
  tags: ["base"]
  roles:
    - role: base
    - role: docker
    - role: network

- hosts: student
  tags: ["student"]
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
  roles:
    - role: consul
    - role: nomad

- hosts: gateway
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
  tags: ["tunnel"]
  roles:
    - role: tunnel

- hosts: primary
  tags: ["primary"]
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
  roles:
    - role: multi-consul
    - role: multi-nomad

- hosts: storage
  tags: ["minio"]
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
  roles:
    - role: minio

- hosts: queue
  tags: ["rabbitmq"]
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
  roles:
    - role: rabbitmq

- hosts:
    - queue
    - storage
    - gateway
    - primary
  tags: ["datadog"]
  roles:
    - role: datadog.datadog
    - role: datadog-conf
  vars:
    datadog_config:
      log_level: INFO
      logs_enabled: true
      process_config:
        enabled: "true"

    system_probe_config:
      sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock

    network_config:
      enabled: true

    runtime_security_config:
      enabled: true

    datadog_additional_groups:
      - systemd-journal
      - docker
      - adm

    datadog_checks:
      docker:
        init_config:

        instances:
          - url: "unix://var/run/docker.sock"
            new_tag_names: true

      journald:
        logs:
          - type: journald
