# docker-compose --env-file .env up --build

services:
  # docker build -t quay.io/cloud-projet/web web/.
  # docker run -p 8080:3000 quay.io/cloud-projet/web
  frontend:
    container_name: cloud-front
    build: web/.
    ports:
      - "8080:3000"

  # docker run -d -p 9000:9000 -p 9001:9001 --rm --name minio quay.io/minio/minio server /data --console-address ":9001"
  minio:
    container_name: cloud-minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    

  # docker run -p 6379:6379 redis:6.2
  db:
    container_name: cloud-db
    image: redis:6.2
    ports:
      - "6379:6379"

  # docker build -t quay.io/cloud-projet/api -f api/Dockerfile.api api
  # docker run -p 8081:8080 --env-file .env quay.io/cloud-projet/api
  api:
    container_name: cloud-api
    build:
      context: api/.
      dockerfile: Dockerfile.api
    ports:
      - "8081:8080"
    env_file:
      - .env


  # docker build -t quay.io/cloud-projet/worker -f api/Dockerfile.worker api
  # docker run --env-file .env quay.io/cloud-projet/worker
  worker:
    container_name: cloud-worker
    build:
      context: api/.
      dockerfile: Dockerfile.worker
    env_file:
      - .env