docker_bridge_range: "10.{{ host_index + 10 }}.0.0/16"
additional_authorized_keys:
  - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP84fwAsjyX4ziJvQ4HZesaVRbvhQvCEYPfKBNBSCWHsnnDQn4o85HAdKceVwcNN/wlfm+AuH9pNpoJgpEEfpy4= sandhose@Quentins-MacBook-Pro.local"

key_to_remove: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCehYenwK8Tz9rDEeQ9/ID4ngZe1iZ7lWfsMTo518RxQKrsbVNPWrVGhcOgB/B6JmMnT1mJzdhJdRY6TN6MYVbVoA4zgAn+TK2w6oJiWK3ryOZrW530fMa88OwO25fj+wK+BPymH4DkvN206yf5DdCGq0thyyD2anIGKr3GzxnGdrD5U1fJi1WsDLB+5oRZUYfKCzs7dBrtPknwWDgg9K/YwVp2aJi0HT+WCWG76+y5AxW9k9HH0XPwCTMfnb3i7hR0q7UmcNG4UPp2LXIGUhiVLMb+TjwPwl4VSycBduv84cZN6IC3tMxNTzK2nhoj+eTp3IMmlDhVFO57yrOzHJ3f Generated-by-Nova"
