# docker build -t cloud-projet/worker -f Dockerfile.worker .
# docker run --env-file ../.env cloud-projet/worker

FROM python:3.11.3-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages
RUN pip install .

# Run app
CMD ["celery", "--app", "image_api.worker.app", "worker"]
