# docker build -t cloud-projet/worker -f Dockerfile.worker .
# docker run cloud-projet/worker

FROM python:3.11.3-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages
RUN pip install .

# Define environment variable
ENV CELERY_BROKER_URL=redis://db:6379/0
ENV S3_ENDPOINT_URL=http://minio:9000

# Run app
CMD ["celery", "--app", "image_api.worker.app", "worker"]
